### ISSUE TITLE
Module Incompatibility: Advanced Macros

### ISSUE THREAD

**Issue by velara** [velara/MercenaryMarketVolume1#26]
The generate a spell list and sorcerous template macros error out when Advanced Macros is enabled. Cause unknown. Will investigate a fix

**Comment by silvative** [comment]
This is a bug with the Advanced Macros module, which breaks most macros used by premium content. However, it should be fixed in the latest version of the Advanced Macros module!

**Comment by velara** [comment]
Awesome, I’ll have to download the updated module and test. If everything works as intended that’ll be wonderful
