### ISSUE TITLE
Assorted typos

### ISSUE THREAD

**Issue by silvative** [velara/MercenaryMarketVolume1#27]
Noticed a few very minor typos as I was exploring the content and thought I'd put them here!

Tactician (all versions): **Opportune Insight** spelled as Opprotune
![image](https://user-images.githubusercontent.com/66365038/170823748-7c65c455-a552-4fee-81a8-b7e3ccd865d1.png)

**Conjurer** (all versions): Spelled as Conjuror. 
Possibly intentional? Both spellings are valid in English, but Conjurer is the spelling used in PF2E. See: Secrets of Magic, page 21
![image](https://user-images.githubusercontent.com/66365038/170823835-6c05fdb9-5680-4e2a-aafc-b7475a3f9345.png)

**Comment by velara** [comment]
Typo corrections are always appreciated. I’ll fix these up for the next release. Thank you!

I couldn’t decide which spelling to use for conjurer, but since there is an official answer from Paizo I’ll use that. I suspects it’s a case of old international English vs American English striking again .

**Comment by velara** [comment]
Ended up keeping my spelling of Conjuror, since its technically valid and changing it involved updating all the conjuror abilities and journal entries as well. But Opportune is now spelled correctly.
