### ISSUE TITLE
Weapons lack Range Increment trait

### ISSUE THREAD

**Issue by jonathanmclaus** [velara/MercenaryMarketVolume1#32]
The strike for Mercenary Ranger and Fighter (and probably others) are missing the Range Increment trait (and defaulting to 10 as a result).

**Comment by velara** [comment]
Thanks so much for the report. Sorry for the slow response. I've gone through all the NPCs and I think found all of the ones that were missing range increment information and corrected them. Should be fixed in 3.02.
