### ISSUE TITLE
Provocateur Troupe [11-12] is missing its publication data

### ISSUE THREAD

**Issue by esheyw** [velara/MercenaryMarketVolume1#33]
Which, in your compendium is still `system.details.source.value`, but in the current system has been moved to `system.details.publication.title`. Migrating would mean requiring system 5.7.x though. Either way, having the data available will prevent edge cases with compendium browser pack/source loading.

**Comment by velara** [comment]
Thanks. I've added the missing data in 3.0.2, I'll tackle migrating (if necessary) in a future release.
