### ISSUE TITLE
Spell List Macro broken

### ISSUE THREAD

**Issue by HongBo-contact** [velara/MercenaryMarketVolume1#34]
Spell Macro does not execute, most likely due to Remaster system changes.

Console:
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/66981178/89d7d740-f559-43e6-81f5-8114688b7197)

**Comment by velara** [comment]
I haven't been able to replicate this exact error. But I am getting an error when running the macro on the post remaster versions, so I'm hoping that the fixes to the errors I'm getting also resolve your error. I've got it running smoothly on the post-remaster version But it needs a little bit of testing before I release it into the wild. 

Should have it released this week.

**Comment by velara** [comment]
Should be fixed in v3.0.3. Please let me know if it is not.
