### ISSUE TITLE
Spell list macro not generating any spells

### ISSUE THREAD

**Issue by Araluen124** [velara/MercenaryMarketVolume1#35]
When i try to generate a spell list for an NPC, i always get an error telling me "cannot generate more spells than exist in the system"

![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/104476123/7e0b8819-438f-4699-aeec-81a8d8e608e3)

**Comment by Malfhast** [comment]
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/70017830/9db96cfc-439f-4c81-ab66-53bbc50b7639)
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/70017830/67c15317-50e2-498f-9131-e3af13a81b30)
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/70017830/35dd1593-3785-49b7-82cf-9c4c375add53)
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/70017830/adaa3d23-f4f7-44d7-aed2-0d1a9c3ebe21)
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/70017830/6d838b63-172f-4704-944a-4dbdbb6f13b8)
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/70017830/ba21f04b-7ff7-4249-9fc7-aaa64b5aa9f5)
![image](https://github.com/velara/MercenaryMarketplaceVolume1/assets/70017830/72b1fbd3-560a-412d-a4fc-71b5322a6b74)

**Comment by velara** [comment]
PF2e 5.9.5 broke my tradition filters, everything worked great in 5.9.4 :(. I've just released a new version that should fix this issue.

**Comment by Malfhast** [comment]
It works, Thank you !
